### PR TITLE
 Edit user persona Betul 

### PR DESCRIPTION
**Pull request by betulaydinturkk**
- [ ] Create a user persona branch
- [ ] Create 1 user persona profile
- [ ] Push + PR

### CODE REVIEW

**Comment by betulaydinturkk** [comment]
I think I fixed it.I changed the branch and and added packages. If it is okey can you approve it? @amirabayoumi @Mamine777

**Comment by amirabayoumi** [comment]
did you deleted? @betulaydinturkk

**Comment by amirabayoumi** [comment]
indeed this one is without an Error,
but i have 2 comment here,:
1- the name of the branch doesn't related to our project 
2- what did you change i can see that you delete your user-persona?

**Comment by betulaydinturkk** [comment]
I couldn't delete but I revert the branch.I will ask coaches that how can I delete user persona?

**Comment by amirabayoumi** [comment]
@betulaydinturkk yes please ask, and put them as reviewer here as well

**Review by KLisabeth — APPROVED** [review]

**Pull request closed without merging**
